### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by ironpeople** [yingkunwu/hand-gesture-recognition#1]
Hi, i really wanted to try your model, but the provided link of poseresnet is broken, can you fix it? Thank youu.

**Comment by yingkunwu** [comment]
Hi, thank you for following this repository. Unfortunately, I lost the original weight as well. I will upload a new one by the end of December. Sorry for any inconvenience.

**Comment by yingkunwu** [comment]
Hi, sorry for the delay. I have just updated the weight and code. Try pulling the latest code and downloading the new weights to try it :)
